### ISSUE TITLE
image

### ISSUE THREAD

**Issue by rlawldn11703** [boostcampaitech5/level1_bookratingprediction-recsys-02#1]
<img width="486" alt="Untitled 1" src="https://user-images.githubusercontent.com/71757471/234790282-2323bbac-8fb5-4567-8e05-1dc11f250f1a.png">
<img width="293" alt="Untitled 2" src="https://user-images.githubusercontent.com/71757471/234790298-89f2ca9f-a6a9-430f-aed2-1da578f0e52c.png">
<img width="373" alt="Untitled 3" src="https://user-images.githubusercontent.com/71757471/234790309-d7f76eec-2fba-4513-90e8-322935d62f9c.png">
<img width="309" alt="Untitled 4" src="https://user-images.githubusercontent.com/71757471/234790313-63ea6f65-563b-441e-8266-43b190838879.png">
![Untitled 5](https://user-images.githubusercontent.com/71757471/234790314-3dab2715-abe8-4e95-ab6a-af0fdf241f2d.png)
<img width="509" alt="Untitled 6" src="https://user-images.githubusercontent.com/71757471/234790316-aec3f40b-609a-4475-b575-dc828bfd0969.png">
<img width="484" alt="Untitled 7" src="https://user-images.githubusercontent.com/71757471/234790320-123712b9-0145-41c1-9a04-f0a9d3ada95c.png">
![Untitled](https://user-images.githubusercontent.com/71757471/234790327-8d894529-81cc-4501-8b7a-c85008c9aa52.png)

**Comment by 0seokim** [comment]
![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/5eafb90a-424b-432f-a3df-ee090c81500e/Untitled.png)

**Comment by 0seokim** [comment]
![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/5eafb90a-424b-432f-a3df-ee090c81500e/Untitled.png)
